// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfcavevnmbnnohatbomz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmY2F2ZXZubWJubm9oYXRib216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDY3ODYsImV4cCI6MjA2MjEyMjc4Nn0.nr2B6bFyiBBxsffz6UhcyaaXBCeRi0z1mEx_5VQWwys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);